/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (NXP) version 5.38                     *
*        Compiled Nov 24 2016, 16:56:53                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: myfont.c                                              *
* Font:        ºÚÌå                                                  *
* Height:      13                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  13                                           *
* Range disabled:       0000 - FFFF                                  *
* Save pattern file: \\Mac\Home\Desktop\Events\lesson_design\UCOS_UCGUI\code\Font\myfont.txt*
* Read pattern file: \\Mac\Home\Desktop\Events\lesson_design\UCOS_UCGUI\code\Font\myfont.txt*
* Read pattern file: \\Mac\Home\Desktop\Events\lesson_design\UCOS_UCGUI\code\Font\myfont.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontmyfont;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_4E8E[ 22] = { /* code 4E8E */
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_5173[ 22] = { /* code 5173 */
  ___X___X,________,
  ___XX__X,________,
  _XXXXXXX,XX______,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  ____X_X_,________,
  ____X_XX,________,
  __XX___X,XX______,
  XX______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_5668[ 22] = { /* code 5668 */
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______,
  _____X__,X_______,
  XXXXXXXX,XXX_____,
  ___XX_XX,________,
  XXX_____,XXX_____,
  _XXXX_XX,XX______,
  _X__X_X_,_X______,
  _XXXX_XX,XX______,
  _X__X_X_,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_5B66[ 24] = { /* code 5B66 */
  ________,________,
  _X__XX__,X_______,
  __X__X__,X_______,
  XXXXXXXX,XXX_____,
  X_______,__X_____,
  X_______,__X_____,
  ___XXXXX,X_______,
  _____XX_,________,
  XXXXXXXX,XXX_____,
  _____X__,________,
  _____X__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_6B22[ 24] = { /* code 6B22 */
  ________,________,
  ______X_,________,
  XXXX__X_,________,
  ___X_XXX,XXX_____,
  ___X_X__,_X______,
  _X_XXX_X,________,
  __X____X,________,
  __XX___X,________,
  _X_X__X_,X_______,
  _X__X_X_,X_______,
  X____X__,_XX_____,
  ____X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_79D1[ 22] = { /* code 79D1 */
  _XXXX___,_X______,
  X_X___X_,_X______,
  __X____X,_X______,
  XXXXX___,_X______,
  __X__XX_,_X______,
  _XXXX_XX,_X______,
  _XX_X___,_XX_____,
  X_X_XXXX,XX______,
  X_X_____,_X______,
  __X_____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_7B97[ 24] = { /* code 7B97 */
  _X_____X,________,
  _XXXX_XX,XXX_____,
  X_XX_XX_,X_______,
  ________,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __X_____,X_______,
  ___XXXXX,________,
  XXXXXXXX,XXXX____,
  ___X___X,________,
  XXX____X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_8BA1[ 22] = { /* code 8BA1 */
  _X_____X,________,
  __X____X,________,
  __X____X,________,
  _______X,________,
  XXXXXXXX,XXX_____,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __XX___X,________,
  __X____X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmyfont_8FCE[ 24] = { /* code 8FCE */
  ________,________,
  _X__XXXX,XXXX____,
  __X_X___,X__X____,
  ____X___,X__X____,
  ____X___,X__X____,
  _XX_X___,X__X____,
  __X_X___,X__X____,
  __X_X_X_,X__X____,
  __X_XX__,X_X_____,
  __X_____,X_______,
  __XX____,________,
  _X__XXXX,XXXX____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontmyfont_CharInfo[9] = {
   {  11,  11,   1,   1,  14, acGUI_Fontmyfont_4E8E } /* code 4E8E */
  ,{  11,  11,   1,   1,  14, acGUI_Fontmyfont_5173 } /* code 5173 */
  ,{  11,  11,   1,   1,  14, acGUI_Fontmyfont_5668 } /* code 5668 */
  ,{  11,  12,   1,   0,  14, acGUI_Fontmyfont_5B66 } /* code 5B66 */
  ,{  12,  12,   1,   0,  14, acGUI_Fontmyfont_6B22 } /* code 6B22 */
  ,{  12,  11,   1,   1,  14, acGUI_Fontmyfont_79D1 } /* code 79D1 */
  ,{  12,  12,   1,   0,  14, acGUI_Fontmyfont_7B97 } /* code 7B97 */
  ,{  11,  11,   1,   1,  14, acGUI_Fontmyfont_8BA1 } /* code 8BA1 */
  ,{  13,  12,   0,   0,  14, acGUI_Fontmyfont_8FCE } /* code 8FCE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop9 = {
   0x8FCE /* first character */
  ,0x8FCE /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  8] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop8 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  7] /* address of first character */
  ,&GUI_Fontmyfont_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop7 = {
   0x7B97 /* first character */
  ,0x7B97 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  6] /* address of first character */
  ,&GUI_Fontmyfont_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop6 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  5] /* address of first character */
  ,&GUI_Fontmyfont_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop5 = {
   0x6B22 /* first character */
  ,0x6B22 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  4] /* address of first character */
  ,&GUI_Fontmyfont_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop4 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  3] /* address of first character */
  ,&GUI_Fontmyfont_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop3 = {
   0x5668 /* first character */
  ,0x5668 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  2] /* address of first character */
  ,&GUI_Fontmyfont_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop2 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  1] /* address of first character */
  ,&GUI_Fontmyfont_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontmyfont_Prop1 = {
   0x4E8E /* first character */
  ,0x4E8E /* last character  */
  ,&GUI_Fontmyfont_CharInfo[  0] /* address of first character */
  ,&GUI_Fontmyfont_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontmyfont = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,13 /* height of font  */
  ,13 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontmyfont_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

