/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.38                          *
*        Compiled Nov 24 2016, 16:57:40                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_1   (GUI_ID_USER + 0x02)
#define ID_TEXT_2   (GUI_ID_USER + 0x03)
#define ID_TEXT_3   (GUI_ID_USER + 0x04)
#define ID_TEXT_4   (GUI_ID_USER + 0x05)
#define ID_TEXT_5   (GUI_ID_USER + 0x06)
#define ID_TEXT_6   (GUI_ID_USER + 0x07)
#define ID_TEXT_7   (GUI_ID_USER + 0x08)
#define ID_TEXT_8   (GUI_ID_USER + 0x09)
#define ID_TEXT_9   (GUI_ID_USER + 0x0A)
#define ID_TEXT_10   (GUI_ID_USER + 0x0B)
#define ID_TEXT_11   (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0   (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 480, 330 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 130, 10, 220, 30 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 100, 50, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 280, 50, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_3, 100, 80, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 280, 80, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 100, 110, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 280, 110, 100, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 170, 145, 140, 30 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 80, 220, 320, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 80, 200, 320, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 80, 180, 360, 20 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 80, 240, 300, 20 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 200, 270, 80, 40 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    FRAMEWIN_SetText(hItem, "About");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, &GUI_Font24B_ASCII);
    TEXT_SetText(hItem, "Best Group Menbers");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, "Qin Kai");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, "Wang Zihan");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, "Liu Xiaowei");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, "Lv Haozheng");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "Miao Yiwei");
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, &GUI_Font16B_ASCII);
    TEXT_SetText(hItem, "He Cenghao");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, &GUI_Font24B_ASCII);
    TEXT_SetText(hItem, "Version Info.");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, &GUI_Font13B_ASCII);
    TEXT_SetText(hItem, "2018.11.1   V0.8    Add more calculation function");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, &GUI_Font13B_ASCII);
    TEXT_SetText(hItem, "2018.11.15 V0.9    Finish all calculation functions");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, &GUI_Font13B_ASCII);
    TEXT_SetText(hItem, "2018.12.1   V1.0    Add beautiful start pic and all done");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, &GUI_Font13B_ASCII);
    TEXT_SetText(hItem, "2018.10.15 V0.5    A simple prototype done");
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_Font24B_ASCII);
    BUTTON_SetText(hItem, "OK");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(hDlg, 1);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       MainTask
*
**********************************************************************
*/
void MainTask_WIDGET_ABOUT(void) {
  WM_HWIN about;
  GUI_Init();
  WM_SetCallback(WM_HBKWIN, _cbDialog);
	about = GUI_ExecDialogBox(_aDialogCreate, 
                      GUI_COUNTOF(_aDialogCreate), 
                      _cbDialog, WM_HBKWIN, 0, 0); /* Create the calculator dialog */

}
// USER END

/*************************** End of file ****************************/
