/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.38                          *
*        Compiled Nov 24 2016, 16:57:40                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*                        Developper: qinkai                          *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "calculator.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x02)
#define ID_TEXT_0   (GUI_ID_USER + 0x03)
#define ID_BUTTON_1   (GUI_ID_USER + 0x04)
#define ID_BUTTON_2   (GUI_ID_USER + 0x05)
#define ID_BUTTON_3   (GUI_ID_USER + 0x06)
#define ID_BUTTON_4   (GUI_ID_USER + 0x07)
#define ID_BUTTON_5   (GUI_ID_USER + 0x08)
#define ID_BUTTON_6   (GUI_ID_USER + 0x09)
#define ID_BUTTON_7   (GUI_ID_USER + 0x0A)
#define ID_BUTTON_8   (GUI_ID_USER + 0x0B)
#define ID_BUTTON_9   (GUI_ID_USER + 0x0C)
#define ID_BUTTON_10   (GUI_ID_USER + 0x0D)
#define ID_BUTTON_11   (GUI_ID_USER + 0x0E)
#define ID_BUTTON_12   (GUI_ID_USER + 0x10)
#define ID_BUTTON_13   (GUI_ID_USER + 0x11)
#define ID_BUTTON_14   (GUI_ID_USER + 0x12)
#define ID_BUTTON_15   (GUI_ID_USER + 0x13)
#define ID_BUTTON_16   (GUI_ID_USER + 0x14)
#define ID_BUTTON_17   (GUI_ID_USER + 0x15)
#define ID_BUTTON_18   (GUI_ID_USER + 0x16)
#define ID_BUTTON_19   (GUI_ID_USER + 0x17)
#define ID_MULTIEDIT_0   (GUI_ID_USER + 0x18)
#define ID_BUTTON_20   (GUI_ID_USER + 0x19)
#define ID_BUTTON_21   (GUI_ID_USER + 0x1A)
#define ID_BUTTON_22   (GUI_ID_USER + 0x1B)
#define ID_BUTTON_23   (GUI_ID_USER + 0x1C)
#define ID_BUTTON_24   (GUI_ID_USER + 0x1D)
#define ID_BUTTON_25   (GUI_ID_USER + 0x1E)
#define ID_BUTTON_26   (GUI_ID_USER + 0x1F)
#define ID_BUTTON_27   (GUI_ID_USER + 0x20)
#define ID_BUTTON_28   (GUI_ID_USER + 0x21)
#define ID_BUTTON_29   (GUI_ID_USER + 0x22)
#define ID_BUTTON_30   (GUI_ID_USER + 0x23)
#define ID_BUTTON_31   (GUI_ID_USER + 0x24)
#define ID_BUTTON_32   (GUI_ID_USER + 0x25)
#define ID_BUTTON_33   (GUI_ID_USER + 0x26)
#define ID_TEXT_1   (GUI_ID_USER + 0x27)
#define ID_BUTTON_34   (GUI_ID_USER + 0x28)
#define ID_TEXT_2   (GUI_ID_USER + 0x29)


// USER START (Optionally insert additional defines)
#define MAXEXPRESSIONLEN 100
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

static GUI_CONST_STORAGE GUI_COLOR _aColorsArrow[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalArrow = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &_aColorsArrow[0]
};

static GUI_CONST_STORAGE unsigned char _acArrowRight[] = {
  ________, ________,XX______,________,
  ________, ________,XXXX____,________,
	________, ________,XXXXXX__,________,
	_____XXX, XXXXXXXX,XXXXXXXX,________,
	_____XXX, XXXXXXXX,XXXXXXXX,XX______,
	_____XXX, XXXXXXXX,XXXXXXXX,________,
	________, ________,XXXXXX__,________,
	________, ________,XXXX____,________,
	________, ________,XX______,________
};

static GUI_CONST_STORAGE unsigned char _acArrowLeft[] = {
  ________, ______XX,________,________,
  ________, ____XXXX,________,________,
	________, __XXXXXX,________,________,
	________, XXXXXXXX,XXXXXXXX,XXX_____,
	______XX, XXXXXXXX,XXXXXXXX,XXX_____,
	________, XXXXXXXX,XXXXXXXX,XXX_____,
	________, __XXXXXX,________,________,
	________, ____XXXX,________,________,
	________, ______XX,________,________
};

static GUI_CONST_STORAGE GUI_BITMAP _bmArrowRight = {
  16,           /* XSize */
  9,            /* YSize */
  4,            /* BytesPerLine */
  2,            /* BitsPerPixel */
  _acArrowRight, /* Pointer to picture data (indices) */
  &_PalArrow     /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmArrowLeft = {
  16,           /* XSize */
  9,            /* YSize */
  4,            /* BytesPerLine */
  2,            /* BitsPerPixel */
  _acArrowLeft,  /* Pointer to picture data (indices) */
  &_PalArrow     /* Pointer to palette */
};

void MULTIEDIT_AddText(WM_HWIN hItem,char* input);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "MyCalculator V1.0", ID_FRAMEWIN_0, 0, 0, 480, 330 },
  { BUTTON_CreateIndirect, "button_1", ID_BUTTON_0, 210, 235, 50, 35 },
  { TEXT_CreateIndirect, "text_equal", ID_TEXT_0, 15, 70, 20, 23 },
  { BUTTON_CreateIndirect, "dot_button", ID_BUTTON_1, 340, 280, 50, 35 },
  { BUTTON_CreateIndirect, "button_0", ID_BUTTON_2, 275, 280, 50, 35 },
  { BUTTON_CreateIndirect, "button_6", ID_BUTTON_3, 340, 190, 50, 35 },
  { BUTTON_CreateIndirect, "button_2", ID_BUTTON_4, 275, 235, 50, 35 },
  { BUTTON_CreateIndirect, "button_4", ID_BUTTON_5, 210, 190, 50, 35 },
  { BUTTON_CreateIndirect, "button_7", ID_BUTTON_6, 210, 145, 50, 35 },
  { BUTTON_CreateIndirect, "button_8", ID_BUTTON_7, 275, 145, 50, 35 },
  { BUTTON_CreateIndirect, "button_9", ID_BUTTON_8, 340, 145, 50, 35 },
  { BUTTON_CreateIndirect, "button_5", ID_BUTTON_9, 275, 190, 50, 35 },
  { BUTTON_CreateIndirect, "button_3", ID_BUTTON_10, 340, 235, 50, 35 },
  { BUTTON_CreateIndirect, "equal_button", ID_BUTTON_11, 405, 280, 50, 35 },
  { BUTTON_CreateIndirect, "minus_button", ID_BUTTON_12, 405, 190, 50, 35 },
  { BUTTON_CreateIndirect, "clear_button", ID_BUTTON_13, 210, 100, 50, 35 },
  { BUTTON_CreateIndirect, "z_button", ID_BUTTON_14, 275, 100, 50, 35 },
  { BUTTON_CreateIndirect, "rest_button", ID_BUTTON_15, 340, 100, 50, 35 },
  { BUTTON_CreateIndirect, "multi_button", ID_BUTTON_16, 405, 145, 50, 35 },
  { BUTTON_CreateIndirect, "devide_button", ID_BUTTON_17, 405, 100, 50, 35 },
  { BUTTON_CreateIndirect, "abs_button", ID_BUTTON_18, 145, 100, 50, 35 },
  { BUTTON_CreateIndirect, "sin_button", ID_BUTTON_19, 145, 190, 50, 35 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 15, 15, 440, 40 },
  { BUTTON_CreateIndirect, "cos_button", ID_BUTTON_20, 145, 145, 50, 35 },
  { BUTTON_CreateIndirect, "lbracket_button", ID_BUTTON_21, 15, 100, 50, 35 },
  { BUTTON_CreateIndirect, "rbracket_button", ID_BUTTON_22, 80, 100, 50, 35 },
  { BUTTON_CreateIndirect, "plus_button", ID_BUTTON_23, 403, 235, 50, 35 },
  { BUTTON_CreateIndirect, "tan_button", ID_BUTTON_24, 145, 235, 50, 35 },
  { BUTTON_CreateIndirect, "log_button", ID_BUTTON_25, 15, 190, 50, 35 },
  { BUTTON_CreateIndirect, "arctan_button", ID_BUTTON_26, 80, 235, 50, 35 },
  { BUTTON_CreateIndirect, "arcsin_button", ID_BUTTON_27, 80, 190, 50, 35 },
  { BUTTON_CreateIndirect, "arccos_button", ID_BUTTON_28, 80, 145, 50, 35 },
  { BUTTON_CreateIndirect, "left_arrow", ID_BUTTON_29, 80, 280, 50, 35 },
  { BUTTON_CreateIndirect, "back_button", ID_BUTTON_30, 15, 280, 50, 35 },
  { BUTTON_CreateIndirect, "right_arrow", ID_BUTTON_31, 145, 280, 50, 35 },
  { BUTTON_CreateIndirect, "sqrt_button", ID_BUTTON_32, 15, 145, 50, 35 },
  { BUTTON_CreateIndirect, "exp_button", ID_BUTTON_33, 15, 235, 50, 35 },
  { TEXT_CreateIndirect, "result", ID_TEXT_1, 38, 65, 350, 30 },
  { BUTTON_CreateIndirect, "backspace_button", ID_BUTTON_34, 210, 280, 50, 35 },
  { TEXT_CreateIndirect, "sign_text", ID_TEXT_2, 310, 70, 144, 18 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	char acBuffer[30];
	int Key;
	char expression[MAXEXPRESSIONLEN];
	char result_text[MAXEXPRESSIONLEN];
	WM_HWIN result;
	result = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MyCalculator V1.0'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    //
    // Initialization of 'button_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "1");
    //
    // Initialization of 'text_equal'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "=");
    TEXT_SetFont(hItem, &GUI_Font24_ASCII);
    //
    // Initialization of 'dot_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, ".");
    //
    // Initialization of 'button_0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetText(hItem, "0");
    //
    // Initialization of 'button_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "6");
    //
    // Initialization of 'button_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetText(hItem, "2");
    //
    // Initialization of 'button_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "4");
    //
    // Initialization of 'button_7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetText(hItem, "7");
    //
    // Initialization of 'button_8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetText(hItem, "8");
    //
    // Initialization of 'button_9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetText(hItem, "9");
    //
    // Initialization of 'button_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetText(hItem, "5");
    //
    // Initialization of 'button_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetText(hItem, "3");
    //
    // Initialization of 'equal_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
    BUTTON_SetText(hItem, "=");
    //
    // Initialization of 'minus_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, &GUI_Font24_ASCII);
    //
    // Initialization of 'clear_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
    BUTTON_SetText(hItem, "C");
    //
    // Initialization of 'z_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
    BUTTON_SetText(hItem, "^");
    //
    // Initialization of 'rest_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
    BUTTON_SetText(hItem, "%");
    //
    // Initialization of 'multi_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
    BUTTON_SetText(hItem, "*");
    BUTTON_SetFont(hItem, &GUI_Font24_ASCII);
    //
    // Initialization of 'devide_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
    BUTTON_SetText(hItem, "/");
    //
    // Initialization of 'abs_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18);
    BUTTON_SetText(hItem, "abs");
    //
    // Initialization of 'sin_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
    BUTTON_SetText(hItem, "sin");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetText(hItem, "");
    MULTIEDIT_SetFont(hItem, &GUI_Font24_ASCII);
		MULTIEDIT_SetAutoScrollH(hItem,1);
		MULTIEDIT_AddKey(hItem,GUI_KEY_INSERT);
		MULTIEDIT_SetMaxNumChars(hItem,100);
		MULTIEDIT_SetBufferSize(hItem,100);
    //
    // Initialization of 'cos_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_20);
    BUTTON_SetText(hItem, "cos");
    //
    // Initialization of 'lbracket_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_21);
    BUTTON_SetText(hItem, "(");
    //
    // Initialization of 'rbracket_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_22);
    BUTTON_SetText(hItem, ")");
    //
    // Initialization of 'plus_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_23);
    BUTTON_SetText(hItem, "+");
    //
    // Initialization of 'tan_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_24);
    BUTTON_SetText(hItem, "tan");
    //
    // Initialization of 'log_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_25);
    BUTTON_SetText(hItem, "log");
    //
    // Initialization of 'arctan_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_26);
    BUTTON_SetText(hItem, "arctan");
    //
    // Initialization of 'arcsin_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_27);
    BUTTON_SetText(hItem, "arcsin");
    //
    // Initialization of 'arccos_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_28);
    BUTTON_SetText(hItem, "arccos");
    //
    // Initialization of 'left_arrow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_29);
		BUTTON_SetText(hItem, "");
    BUTTON_SetBitmapEx(hItem, 0, &_bmArrowLeft, 17, 13); /* Set bitmap for arrow right button (unpressed) */
    BUTTON_SetBitmapEx(hItem, 1, &_bmArrowLeft, 17, 13); /* Set bitmap for arrow right button (pressed) */
    //
    // Initialization of 'back_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_30);
    BUTTON_SetText(hItem, "back");
    //
    // Initialization of 'right_arrow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_31);
		BUTTON_SetText(hItem, "");
    BUTTON_SetBitmapEx(hItem, 0, &_bmArrowRight, 17, 13); /* Set bitmap for arrow right button (unpressed) */
    BUTTON_SetBitmapEx(hItem, 1, &_bmArrowRight, 17, 13); /* Set bitmap for arrow right button (pressed) */
    //
    // Initialization of 'sqrt_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_32);
    BUTTON_SetText(hItem, "sqrt");
    //
    // Initialization of 'exp_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_33);
    BUTTON_SetText(hItem, "exp");
    //
    // Initialization of 'result'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, &GUI_Font24_ASCII);
    TEXT_SetText(hItem, "0");
    //
    // Initialization of 'backspace_button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_34);
    BUTTON_SetText(hItem, "del");
    //
    // Initialization of 'sign_text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    //TEXT_SetText(hItem, " ----developed by qinkai");
		TEXT_SetText(hItem, " ");
    TEXT_SetFont(hItem, &GUI_Font16_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'button_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'1');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'dot_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'.');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'button_0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'0');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'button_6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'6');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'button_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'2');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'button_4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'4');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'button_7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'7');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'button_8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'8');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'button_9'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'9');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'button_5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'5');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'button_3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'3');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'equal_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_GetText(hItem,expression,MAXEXPRESSIONLEN);
				calc(expression,result_text);
				TEXT_SetText(result,result_text);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'minus_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'-');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'clear_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_SetText(hItem,"");
				TEXT_SetText(result,"0");
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by 'z_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'^');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by 'rest_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'%');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'multi_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'*');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_17: // Notifications sent by 'devide_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'/');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_18: // Notifications sent by 'abs_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'b');
				MULTIEDIT_AddKey(hItem,'s');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_19: // Notifications sent by 'sin_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'s');
				MULTIEDIT_AddKey(hItem,'i');
				MULTIEDIT_AddKey(hItem,'n');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,GUI_KEY_INSERT);
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_20: // Notifications sent by 'cos_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'c');
				MULTIEDIT_AddKey(hItem,'o');
				MULTIEDIT_AddKey(hItem,'s');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_21: // Notifications sent by 'lbracket_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'(');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_22: // Notifications sent by 'rbracket_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,')');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_23: // Notifications sent by 'plus_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'+');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_24: // Notifications sent by 'tan_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'t');
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'n');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_25: // Notifications sent by 'log_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'l');
				MULTIEDIT_AddKey(hItem,'o');
				MULTIEDIT_AddKey(hItem,'g');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_26: // Notifications sent by 'arctan_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'r');
				MULTIEDIT_AddKey(hItem,'c');
				MULTIEDIT_AddKey(hItem,'t');
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'n');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_27: // Notifications sent by 'arcsin_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'r');
				MULTIEDIT_AddKey(hItem,'c');
				MULTIEDIT_AddKey(hItem,'s');
				MULTIEDIT_AddKey(hItem,'i');
				MULTIEDIT_AddKey(hItem,'n');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_28: // Notifications sent by 'arccos_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'a');
				MULTIEDIT_AddKey(hItem,'r');
				MULTIEDIT_AddKey(hItem,'c');
				MULTIEDIT_AddKey(hItem,'c');
				MULTIEDIT_AddKey(hItem,'o');
				MULTIEDIT_AddKey(hItem,'s');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_29: // Notifications sent by 'left_arrow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,GUI_KEY_LEFT);
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_30: // Notifications sent by 'back_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				GUI_EndDialog(hDlg, 1);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_31: // Notifications sent by 'right_arrow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,GUI_KEY_RIGHT);
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_32: // Notifications sent by 'sqrt_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'s');
				MULTIEDIT_AddKey(hItem,'q');
				MULTIEDIT_AddKey(hItem,'r');
				MULTIEDIT_AddKey(hItem,'t');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_33: // Notifications sent by 'exp_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,'e');
				MULTIEDIT_AddKey(hItem,'x');
				MULTIEDIT_AddKey(hItem,'p');
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_34: // Notifications sent by 'backspace_button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				MULTIEDIT_AddKey(hItem,GUI_KEY_BACKSPACE);
				WM_SetFocus(hItem);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMyCalculator V1.0
*/
WM_HWIN CreateMyCalculator_V1_0(void);
WM_HWIN CreateMyCalculator_V1_0(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

/*********************************************************************
*
*       MainTask
*
**********************************************************************
*/
void MainTask_WIDGET_CALCULATOR(void) {
  WM_HWIN calculator;
  GUI_Init();
  WM_SetCallback(WM_HBKWIN, _cbDialog);
	calculator = GUI_ExecDialogBox(_aDialogCreate, 
                      GUI_COUNTOF(_aDialogCreate), 
                      _cbDialog, WM_HBKWIN, 0, 0); /* Create the calculator dialog */

}
// USER END

/*************************** End of file ****************************/
